#!/bin/bash

Kern=`uname -r`
RAM=`free -h | awk '/^Mem:/ {print $3 "/" $2}'`

DU=`df -h /dev/sda2 --output=used,size | awk 'NR==2 {print $1 "/" $2}'`

type -fP acpi > /dev/null 2>&1 && Bat=`acpi -b | awk '/B/ {print "Battery: " $4}'`

Users=`users`

CPU_Temp(){
	awk '
		{
			if(NR=/Core [0-3]/){
				if($2~/^[0-3]:$/){
					$2=substr($2, 0, 1)
				}

				if(substr($3, 0, 1) ~ /^+$/){
					printf("  Core %s: %s\n", $2+1, substr($3, 2))
				}else{
					printf("  Core %s: %s\n", $2+1, $3)
				}
			}
		}
	' <<< "$(sensors)"
}

[ $UID -eq 0 ] && HDD_Temp=`hddtemp /dev/sda2 | cut -d ' ' -f 4`

cat <<-EOF

	===========================
	    SYSTEM INFORMATION
	===========================

	Kernel: ${Kern:-N/A}

	Memory Usage: ${RAM:-N/A}


	Disk Usage for HDD: ${DU:-N/A}


	Battery: ${Bat:-N/A}

	Active Users: ${Users:-N/A}

	CPU Temperature (By Core):

	`CPU_Temp`

	HDD Temperature: ${HDD_Temp:-N/A}

EOF
