#!/bin/bash
echo
echo "==========================="
echo "    SYSTEM INFORMATION"
echo "==========================="
echo
uname -r | awk '{print "Kernel: " $1}'
echo
free -mh | awk '/Mem:/ {print "Memory Usage: " $3 "/" $2}'
echo
df -h | awk '/\/dev\/root/ {print "Disk Usage for HDD: " $3 "/" $2}'
echo
echo -n "Active Users: "
users
echo
/opt/vc/bin/vcgencmd measure_temp | cut -c 6- | awk '{print "CPU Temperature: " $1}'
echo
